Added logging and zip'd all files in Azure, AWS, GCP Scripts
rubrikinc/rubrik-sizing-scripts pull request #35
Opened 2024-07-08 22:20 UTC by vpritamani-rubrik

2024-07-10 15:54 UTC, DamaniN requested changes
@vpritamani-rubrik, please add instructional lines, telling the user to send the zip file to their Rubrik representative.

2024-07-10 15:54 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
> +Write-Host "Results have been compressed into $archiveFile and original files have been removed." -ForegroundColor Green
@vpritamani-rubrik, please add an instructional line after this, telling the user to send the zip file to their Rubrik representative.

2024-07-10 15:54 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
> +Write-Host "Results have been compressed into $archiveFile and original files have been removed." -ForegroundColor Green
@vpritamani-rubrik, please add an instructional line after this, telling the user to send the zip file to their Rubrik representative.

2024-07-10 15:54 UTC, DamaniN commented on CLOUD/Get-GCPSizingInfo.ps1
> +Write-Host "Results have been compressed into $archiveFile and original files have been removed." -ForegroundColor Green
@vpritamani-rubrik, please add an instructional line after this, telling the user to send the zip file to their Rubrik representative.

2024-07-10 16:34 UTC, vpritamani-rubrik commented
Added instructional lines to all files @DamaniN

2024-07-10 23:02 UTC, DamaniN requested changes
@vpritamani-rubrik while testing this I found that if I CTL-C the script that the transcript is still going. Everything else I do at the prompt is written to the output.log file. You'll need to find a way to capture break signals and exit the script gracefully by running Stop-Transcript first.

2024-07-10 23:06 UTC, DamaniN requested changes
@vpritamani-rubrik the Start-Transcript command doesn't appear to zero out the output.log file before writing to it. Instead, the file is appended to. You'll need to figure out if the output.log file exists already. If it does, you'll need to delete it.

2024-07-11 00:48 UTC, vpritamani-rubrik commented
@DamaniN Only way I could find to handle break-signals and still Stopping Transcript is by putting the whole thing in a try-catch-finally, hence I implemented it like that. Also cleared existing log file if exists before writing to it as requested

2024-07-15 21:29 UTC, DamaniN reviewed
LGTM

2024-07-15 21:30 UTC, DamaniN approved these changes
LGTM

2024-07-15 21:30 UTC, merged