Made Additional Changes
rubrikinc/rubrik-sizing-scripts pull request #39
Opened 2024-08-06 16:51 UTC by vpritamani-rubrik

Changes include:
- Azure Backup Costs
- Anonymization Feature
- Improving consolidation script
- Separate MI SQL and SQL, added LTR/STR data for MI SQL
- Fixing potential region issues giving commas instead of .'s in CSV output

2024-08-13 07:27 UTC, DamaniN requested changes
There are a few issues to fix. Review the comments on each file.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-GCPSizingInfo.ps1
I ran this script twice in the same minute. When I did so, I got this error message:

```
Compress-Archive: /Users/<redacted>/Downloads/Sizing-Script-Testing/<redacted>/rubrik-sizing-scripts/CLOUD/Get-GCPSizingInfo.ps1:341
Line |
 341 |  Compress-Archive -Path $existingFiles -DestinationPath $archiveFile
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The archive file /Users/<redacted>/Downloads/Sizing-Script-Testing/<redaced>/rubrik-sizing-scripts/CLOUD/gcp_sizing_results_2024-08-12_2155.zip
     | already exists. Use the -Update parameter to update the existing archive file or use the -Force parameter to overwrite the existing archive file.
```

We should check to see if the archive file exists and rename it before proceeding. This should be done in the AWS and GCP scripts as well.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-GCPSizingInfo.ps1
The `-Anonymize` feature uses letters to represent anonymized objects. This won't scale very well. Some customers may have 10s of thousands of objects. Instead, use the object type as the prefix and a padded number as the suffix. The padded number should support up to 100,000 objects. As an example, VMs should be:

````
vm-00000
vm-00001
vm-00002
.
.
.
vm-03945
vm-03946
```

Projects should be:

```
project-00000
project-00001
project-00002
.
.
.
```

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
The -Anonymize feature uses letters to represent anonymized objects. This won't scale very well. Some customers may have 10s of thousands of objects. Instead, use the object type as the prefix and a padded number as the suffix. The padded number should support up to 100,000 objects.  See the GCP script comments for examples.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
The -Anonymize feature uses letters to represent anonymized objects. This won't scale very well. Some customers may have 10s of thousands of objects. Instead, use the object type as the prefix and a padded number as the suffix. The padded number should support up to 100,000 objects.  See the GCP script comments for examples.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-GCPSizingInfo.ps1
The `-Anonymize` key file should have a date time suffix that matches the zip file. This way, if the script is run multiple times, the key file will match the zip file.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
The `-Anonymize` key file should have a date time suffix that matches the zip file. This way, if the script is run multiple times, the key file will match the zip file.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
The `-Anonymize` key file should have a date time suffix that matches the zip file. This way, if the script is run multiple times, the key file will match the zip file.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-GCPSizingInfo.ps1
The `-Anonymize` key file does not contain a key for the project IDs.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
The `-Anonymize` doesn't anonymize any of the data in the `s3_info` CSV files.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
The -Anonymize function needs to anonymize the following fields in each file:

Tag keys
Backup Plan Names

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
> +Write-Host "Net unblended cost of AWS Backup for past 12 months + this month so far: $ $backupTotalNetUnblendedCost"  -ForegroundColor Green
There is an extra space between the dollar sign here and the value. Example:

```
Net unblended cost of AWS Backup for past 12 months + this month so far: $ 24110.49
```

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
The `-Anonymize` function on the `aws-backup-plans-info` file needs to anonymize the following fields:

- BackupPlanName (should match what's in the CSVs)
- DestinationBackupVaultArn
  - And any other ARN
  - Only anonymize the account number and ARN name. Leave the path intact.
- Resources 
  - Only anonymize the resource ID. Leave the path intact
- Project
- TargetBackupVaultName
- CreatorRequestId
  - Only anonymize the ID, leave the path intact.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AWSSizingInfo.ps1
The `-Anonymize` function does not appear to be anonymizing the data in the `output.log`

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
The -Anonymize function does not appear to be anonymizing the data in the output.log

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-GCPSizingInfo.ps1
The -Anonymize function does not appear to be anonymizing the data in the output.log

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
The `-Anonymize` function needs to anonymize the following fields in the `azure_backup_vault_VM_policies` JSON file:

- AzureBackupRGName

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
Where applicable, the `-Anonymize` function needs to anonymize the key name of any tags.

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
In the `azure_mi_db_items` JSON files the `-Anonymize` function must anonymize the following fields:

- Id
  - Leave the path intact only anonymize the subscription ID, resource group ID, managed instance name and database name. 
  - The IDs and names should match the corresponding file. 
- ResourceGroupName
- DatabaseName
- ManagedInstanceName
- Name
- InstanceName

2024-08-13 07:27 UTC, DamaniN commented on CLOUD/Get-AzureSizingInfo.ps1
The `azure_vmdisk_info` CSV file is corrupted. I'll DM you an example of what's in it.

2024-08-13 15:54 UTC, vpritamani-rubrik commented on CLOUD/Get-GCPSizingInfo.ps1
This only happens when the archive file is the same name - as the archive file is named based on the hour and minute it runs, this 'error' only occurs if someone tries to run the script multiple times in the same minute, which shouldn't happen

2024-08-13 16:51 UTC, vpritamani-rubrik commented on CLOUD/Get-GCPSizingInfo.ps1
I implemented this but with regular numbers and not padded numbers

2024-08-13 18:28 UTC, vpritamani-rubrik commented on CLOUD/Get-AWSSizingInfo.ps1
For the ARNs, the problem with AWS is that these are not consistent across different resource types/workloads. One can see these inconsistencies in how I have to process the ARNs when assigning backup plans to resources.

2024-08-13 22:13 UTC, vpritamani-rubrik commented on CLOUD/Get-GCPSizingInfo.ps1
Will add seconds

2024-08-13 22:32 UTC, vpritamani-rubrik commented on CLOUD/Get-GCPSizingInfo.ps1
Will make the anonymize tag exclude the output log from the ZIP file, keep it in the system. Add note for customer to sanitize output log before sending.

Create a output log in ZIP to just say "Anonymized file; customer has original"

2024-08-14 18:59 UTC, vpritamani-rubrik commented
@DamaniN Fixed all of the issues incorporating feedback from our talk yesterday

2024-09-03 03:58 UTC, DamaniN approved these changes
Logged a few issues in our internal tracker to push out this PR. All other changes look good.

2024-09-03 03:58 UTC, merged